// Login
export const LOGIN_PAGE_SHOW_LOGIN_FORM = 'LOGIN_PAGE_SHOW_LOGIN_FORM';
export const RESET_LOGIN_PAGE = 'RESET_LOGIN_PAGE';
export const UPDATE_LOGIN_PAGE_FORM_FIELD = 'UPDATE_LOGIN_PAGE_FORM_FIELD';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// Events List
export const GET_EVENTS_LIST_REQUEST = 'GET_EVENTS_LIST_REQUEST';
export const GET_EVENTS_LIST_SUCCESS = 'GET_EVENTS_LIST_SUCCESS';
export const GET_EVENTS_LIST_ERROR = 'GET_EVENTS_LIST_ERROR';

export const RESET_EVENTS_LIST_META = 'RESET_EVENTS_LIST_META';
export const RESET_EVENTS_LIST_PAGE = 'RESET_EVENTS_LIST_PAGE';

// Event Detail - Basic
export const GET_EVENT_BASIC_REQUEST = 'GET_EVENT_BASIC_REQUEST';
export const GET_EVENT_BASIC_SUCCESS = 'GET_EVENT_BASIC_SUCCESS';
export const GET_EVENT_BASIC_ERROR = 'GET_EVENT_BASIC_ERROR';

export const GET_EVENT_BASIC_ASSET_FILE_REQUEST = 'GET_EVENT_BASIC_ASSET_FILE_REQUEST';
export const GET_EVENT_BASIC_ASSET_FILE_SUCCESS = 'GET_EVENT_BASIC_ASSET_FILE_SUCCESS';
export const GET_EVENT_BASIC_ASSET_FILE_ERROR = 'GET_EVENT_BASIC_ASSET_FILE_ERROR';

export const SUBMIT_EVENT_BASIC_REQUEST = 'SUBMIT_EVENT_BASIC_REQUEST';
export const SUBMIT_EVENT_BASIC_SUCCESS = 'SUBMIT_EVENT_BASIC_SUCCESS';
export const SUBMIT_EVENT_BASIC_ERROR = 'SUBMIT_EVENT_BASIC_ERROR';

export const RESET_EVENT_BASIC_META = 'RESET_EVENT_BASIC_META';
export const RESET_EVENT_BASIC_PAGE = 'RESET_EVENT_BASIC_PAGE';

// Event Detail - Participant Form
export const GET_EVENT_FORM_FIELDS_REQUEST = 'GET_EVENT_FORM_FIELDS_REQUEST';
export const GET_EVENT_FORM_FIELDS_SUCCESS = 'GET_EVENT_FORM_FIELDS_SUCCESS';
export const GET_EVENT_FORM_FIELDS_ERROR = 'GET_EVENT_FORM_FIELDS_ERROR';

export const SET_NULL_EVENT_FORM_FIELD = 'SET_NULL_EVENT_FORM_FIELD';

export const GET_EVENT_FORM_FIELD_BY_ID_REQUEST = 'GET_EVENT_FORM_FIELD_BY_ID_REQUEST';
export const GET_EVENT_FORM_FIELD_BY_ID_SUCCESS = 'GET_EVENT_FORM_FIELD_BY_ID_SUCCESS';
export const GET_EVENT_FORM_FIELD_BY_ID_ERROR = 'GET_EVENT_FORM_FIELD_BY_ID_ERROR';

export const SUBMIT_EVENT_FORM_FIELD_REQUEST = 'SUBMIT_EVENT_FORM_FIELD_REQUEST';
export const SUBMIT_EVENT_FORM_FIELD_SUCCESS = 'SUBMIT_EVENT_FORM_FIELD_SUCCESS';
export const SUBMIT_EVENT_FORM_FIELD_ERROR = 'SUBMIT_EVENT_FORM_FIELD_ERROR';

export const DELETE_EVENT_FORM_FIELD_REQUEST = 'DELETE_EVENT_FORM_FIELD_REQUEST';
export const DELETE_EVENT_FORM_FIELD_SUCCESS = 'DELETE_EVENT_FORM_FIELD_SUCCESS';
export const DELETE_EVENT_FORM_FIELD_ERROR = 'DELETE_EVENT_FORM_FIELD_ERROR';

export const RESET_EVENT_PARTICIPANT_FORM_META = 'RESET_EVENT_PARTICIPANT_FORM_META';
export const RESET_EVENT_PARTICIPANT_FORM_PAGE = 'RESET_EVENT_PARTICIPANT_FORM_PAGE';

// Event Detail - Price Group
export const GET_EVENT_PRICE_GROUPS_REQUEST = 'GET_EVENT_PRICE_GROUPS_REQUEST';
export const GET_EVENT_PRICE_GROUPS_SUCCESS = 'GET_EVENT_PRICE_GROUPS_SUCCESS';
export const GET_EVENT_PRICE_GROUPS_ERROR = 'GET_EVENT_PRICE_GROUPS_ERROR';

export const SET_NULL_EVENT_PRICE_GROUP = 'SET_NULL_EVENT_PRICE_GROUP';

export const GET_EVENT_PRICE_GROUP_BY_ID_REQUEST = 'GET_EVENT_PRICE_GROUP_BY_ID_REQUEST';
export const GET_EVENT_PRICE_GROUP_BY_ID_SUCCESS = 'GET_EVENT_PRICE_GROUP_BY_ID_SUCCESS';
export const GET_EVENT_PRICE_GROUP_BY_ID_ERROR = 'GET_EVENT_PRICE_GROUP_BY_ID_ERROR';

export const GET_EVENT_PRICING_USER_TYPES_REQUEST = 'GET_EVENT_PRICING_USER_TYPES_REQUEST';
export const GET_EVENT_PRICING_USER_TYPES_SUCCESS = 'GET_EVENT_PRICING_USER_TYPES_SUCCESS';
export const GET_EVENT_PRICING_USER_TYPES_ERROR = 'GET_EVENT_PRICING_USER_TYPES_ERROR';

export const SUBMIT_EVENT_PRICE_GROUP_REQUEST = 'SUBMIT_EVENT_PRICE_GROUP_REQUEST';
export const SUBMIT_EVENT_PRICE_GROUP_SUCCESS = 'SUBMIT_EVENT_PRICE_GROUP_SUCCESS';
export const SUBMIT_EVENT_PRICE_GROUP_ERROR = 'SUBMIT_EVENT_PRICE_GROUP_ERROR';

export const DELETE_EVENT_PRICE_GROUP_REQUEST = 'DELETE_EVENT_PRICE_GROUP_REQUEST';
export const DELETE_EVENT_PRICE_GROUP_SUCCESS = 'DELETE_EVENT_PRICE_GROUP_SUCCESS';
export const DELETE_EVENT_PRICE_GROUP_ERROR = 'DELETE_EVENT_PRICE_GROUP_ERROR';

export const RESET_EVENT_PRICING_META = 'RESET_EVENT_PRICING_META';
export const RESET_EVENT_PRICING_PAGE = 'RESET_EVENT_PRICING_PAGE';

// EventDetailPage.EventNotificationsPage
export const GET_EVENT_NOTIFICATIONS_ERROR = 'GET_EVENT_NOTIFICATIONS_ERROR';
export const GET_EVENT_NOTIFICATIONS_REQUEST = 'GET_EVENT_NOTIFICATIONS_REQUEST';
export const GET_EVENT_NOTIFICATIONS_SUCCESS = 'GET_EVENT_NOTIFICATIONS_SUCCESS';
export const RESET_EVENT_NOTIFICATIONS_META = 'RESET_EVENT_NOTIFICATIONS_META';
export const RESET_EVENT_NOTIFICATIONS_PAGE = 'RESET_EVENT_NOTIFICATIONS_PAGE';

// EventDetailPage.EventNotificationDetailPage
export const GET_EVENT_NOTIFICATION_DETAIL_ERROR = 'GET_EVENT_NOTIFICATION_DETAIL_ERROR';
export const GET_EVENT_NOTIFICATION_DETAIL_REQUEST = 'GET_EVENT_NOTIFICATION_DETAIL_REQUEST';
export const GET_EVENT_NOTIFICATION_DETAIL_SUCCESS = 'GET_EVENT_NOTIFICATION_DETAIL_SUCCESS';
export const RESET_EVENT_NOTIFICATION_DETAIL_META = 'RESET_EVENT_NOTIFICATION_DETAIL_META';
export const RESET_EVENT_NOTIFICATION_DETAIL_PAGE = 'RESET_EVENT_NOTIFICATION_DETAIL_PAGE';
export const SCHEDULE_EVENT_NOTIFICATION_DETAIL_ERROR = 'SCHEDULE_EVENT_NOTIFICATION_DETAIL_ERROR';
export const SCHEDULE_EVENT_NOTIFICATION_DETAIL_REQUEST = 'SCHEDULE_EVENT_NOTIFICATION_DETAIL_REQUEST';
export const SCHEDULE_EVENT_NOTIFICATION_DETAIL_SUCCESS = 'SCHEDULE_EVENT_NOTIFICATION_DETAIL_SUCCESS';
export const SEND_EVENT_NOTIFICATION_DETAIL_ERROR = 'SEND_EVENT_NOTIFICATION_DETAIL_ERROR';
export const SEND_EVENT_NOTIFICATION_DETAIL_REQUEST = 'SEND_EVENT_NOTIFICATION_DETAIL_REQUEST';
export const SEND_EVENT_NOTIFICATION_DETAIL_SUCCESS = 'SEND_EVENT_NOTIFICATION_DETAIL_SUCCESS';
export const SUBMIT_EVENT_NOTIFICATION_DETAIL_ERROR = 'SUBMIT_EVENT_NOTIFICATION_DETAIL_ERROR';
export const SUBMIT_EVENT_NOTIFICATION_DETAIL_REQUEST = 'SUBMIT_EVENT_NOTIFICATION_DETAIL_REQUEST';
export const SUBMIT_EVENT_NOTIFICATION_DETAIL_SUCCESS = 'SUBMIT_EVENT_NOTIFICATION_DETAIL_SUCCESS';

// OnboardingScreens
export const GET_ONBOARDINGSCREENS_PAGE_REQUEST = 'GET_ONBOARDINGSCREENS_PAGE_REQUEST';
export const GET_ONBOARDINGSCREENS_PAGE_SUCCESS = 'GET_ONBOARDINGSCREENS_PAGE_SUCCESS';
export const GET_ONBOARDINGSCREENS_PAGE_ERROR = 'GET_ONBOARDINGSCREENS_PAGE_ERROR';
export const RESET_ONBOARDINGSCREENS_PAGE_META = 'RESET_ONBOARDINGSCREENS_PAGE_META';
export const RESET_ONBOARDINGSCREENS_PAGE = 'RESET_ONBOARDINGSCREENS_PAGE';

export const GET_ONBOARDINGSCREENS_DETAIL_PAGE_REQUEST = 'GET_ONBOARDINGSCREENS_DETAIL_PAGE_REQUEST';
export const GET_ONBOARDINGSCREENS_DETAIL_PAGE_SUCCESS = 'GET_ONBOARDINGSCREENS_DETAIL_PAGE_SUCCESS';
export const GET_ONBOARDINGSCREENS_DETAIL_PAGE_ERROR = 'GET_ONBOARDINGSCREENS_DETAIL_PAGE_ERROR';
export const RESET_ONBOARDINGSCREENS_DETAIL_PAGE_META = 'RESET_ONBOARDINGSCREENS_DETAIL_PAGE_META';
export const RESET_ONBOARDINGSCREENS_DETAIL_PAGE = 'RESET_ONBOARDINGSCREENS_DETAIL_PAGE';

export const GET_ONBOARDINGSCREEN_BY_ID_PAGE_SUCCESS = 'GET_ONBOARDINGSCREEN_BY_ID_PAGE_SUCCESS';
export const GET_ONBOARDINGSCREEN_BY_ID_PAGE_ERROR = 'GET_ONBOARDINGSCREEN_BY_ID_PAGE_ERROR';
export const GET_ONBOARDINGSCREEN_BY_ID_PAGE_REQUEST = 'GET_ONBOARDINGSCREEN_BY_ID_PAGE_REQUEST';

export const SUBMIT_ADD_ONBOARD_SCREEN_REQUEST = 'SUBMIT_ADD_ONBOARD_SCREEN_REQUEST';
export const SUBMIT_ADD_ONBOARD_SCREEN_SUCCESS = 'SUBMIT_ADD_ONBOARD_SCREEN_SUCCESS';
export const SUBMIT_ADD_ONBOARD_SCREEN_ERROR = 'SUBMIT_ADD_ONBOARD_SCREEN_ERROR';

export const DELETE_ONBOARD_SCREEN_REQUEST = 'DELETE_ONBOARD_SCREEN_REQUEST';
export const DELETE_ONBOARD_SCREEN_SUCCESS = 'DELETE_ONBOARD_SCREEN_SUCCESS';
export const DELETE_ONBOARD_SCREEN_ERROR = 'DELETE_ONBOARD_SCREEN_ERROR';

// News
export const RESET_NEWS_PAGE_META = 'RESET_NEWS_PAGE_META';
export const RESET_NEWS_PAGE = 'RESET_NEWS_PAGE';
export const GET_NEWS_PAGE_REQUEST = 'GET_NEWS_PAGE_REQUEST';
export const GET_NEWS_PAGE_ERROR = 'GET_NEWS_PAGE_ERROR';
export const GET_NEWS_PAGE_SUCCESS = 'GET_NEWS_PAGE_SUCCESS';

export const RESET_NEWS_DETAIL_PAGE_META = 'RESET_NEWS_DETAIL_PAGE_META';
export const RESET_NEWS_DETAIL_PAGE = 'RESET_NEWS_DETAIL_PAGE';

export const CREATE_NEWS_REQUEST = 'CREATE_NEWS_REQUEST';
export const CREATE_NEWS_ERROR = 'CREATE_NEWS_ERROR';
export const CREATE_NEWS_SUCCESS = 'CREATE_NEWS_SUCCESS';

export const GET_NEWS_BY_ID_REQUEST = 'GET_NEWS_BY_ID_REQUEST';
export const GET_NEWS_BY_ID_ERROR = 'GET_NEWS_BY_ID_ERROR';
export const GET_NEWS_BY_ID_SUCCESS = 'GET_NEWS_BY_ID_SUCCESS';

// NewsDetailPage.NewsNotificationsPage
export const GET_NEWS_NOTIFICATIONS_ERROR = 'GET_NEWS_NOTIFICATIONS_ERROR';
export const GET_NEWS_NOTIFICATIONS_REQUEST = 'GET_NEWS_NOTIFICATIONS_REQUEST';
export const GET_NEWS_NOTIFICATIONS_SUCCESS = 'GET_NEWS_NOTIFICATIONS_SUCCESS';
export const RESET_NEWS_NOTIFICATIONS_META = 'RESET_NEWS_NOTIFICATIONS_META';
export const RESET_NEWS_NOTIFICATIONS_PAGE = 'RESET_NEWS_NOTIFICATIONS_PAGE';

// NewsDetailPage.NewsNotificationDetailPage
export const GET_NEWS_NOTIFICATION_DETAIL_ERROR = 'GET_NEWS_NOTIFICATION_DETAIL_ERROR';
export const GET_NEWS_NOTIFICATION_DETAIL_REQUEST = 'GET_NEWS_NOTIFICATION_DETAIL_REQUEST';
export const GET_NEWS_NOTIFICATION_DETAIL_SUCCESS = 'GET_NEWS_NOTIFICATION_DETAIL_SUCCESS';
export const RESET_NEWS_NOTIFICATION_DETAIL_META = 'RESET_NEWS_NOTIFICATION_DETAIL_META';
export const RESET_NEWS_NOTIFICATION_DETAIL_PAGE = 'RESET_NEWS_NOTIFICATION_DETAIL_PAGE';
export const SCHEDULE_NEWS_NOTIFICATION_DETAIL_ERROR = 'SCHEDULE_NEWS_NOTIFICATION_DETAIL_ERROR';
export const SCHEDULE_NEWS_NOTIFICATION_DETAIL_REQUEST = 'SCHEDULE_NEWS_NOTIFICATION_DETAIL_REQUEST';
export const SCHEDULE_NEWS_NOTIFICATION_DETAIL_SUCCESS = 'SCHEDULE_NEWS_NOTIFICATION_DETAIL_SUCCESS';
export const SEND_NEWS_NOTIFICATION_DETAIL_ERROR = 'SEND_NEWS_NOTIFICATION_DETAIL_ERROR';
export const SEND_NEWS_NOTIFICATION_DETAIL_REQUEST = 'SEND_NEWS_NOTIFICATION_DETAIL_REQUEST';
export const SEND_NEWS_NOTIFICATION_DETAIL_SUCCESS = 'SEND_NEWS_NOTIFICATION_DETAIL_SUCCESS';
export const SUBMIT_NEWS_NOTIFICATION_DETAIL_ERROR = 'SUBMIT_NEWS_NOTIFICATION_DETAIL_ERROR';
export const SUBMIT_NEWS_NOTIFICATION_DETAIL_REQUEST = 'SUBMIT_NEWS_NOTIFICATION_DETAIL_REQUEST';
export const SUBMIT_NEWS_NOTIFICATION_DETAIL_SUCCESS = 'SUBMIT_NEWS_NOTIFICATION_DETAIL_SUCCESS';


// Events
export const GET_EVENTS_PAGE_REQUEST = 'GET_EVENTS_PAGE_REQUEST';
export const GET_EVENTS_PAGE_SUCCESS = 'GET_EVENTS_PAGE_SUCCESS';
export const GET_EVENTS_PAGE_ERROR = 'GET_EVENTS_PAGE_ERROR';
export const RESET_EVENTS_PAGE_META = 'RESET_EVENTS_PAGE_META';
export const RESET_EVENTS_PAGE = 'RESET_EVENTS_PAGE';

// Events Registration
export const GET_EVENT_REGISTRATIONS_REQUEST = 'GET_EVENT_REGISTRATIONS_REQUEST';
export const GET_EVENT_REGISTRATIONS_SUCCESS = 'GET_EVENT_REGISTRATIONS_SUCCESS';
export const GET_EVENT_REGISTRATIONS_ERROR = 'GET_EVENT_REGISTRATIONS_ERROR';

export const GET_EVENT_REGISTRATION_DETAIL_REQUEST = 'GET_EVENT_REGISTRATION_DETAIL_REQUEST';
export const GET_EVENT_REGISTRATION_DETAIL_SUCCESS = 'GET_EVENT_REGISTRATION_DETAIL_SUCCESS';
export const GET_EVENT_REGISTRATION_DETAIL_ERROR = 'GET_EVENT_REGISTRATION_DETAIL_ERROR';

export const RESET_EVENT_REGISTRATIONS_META = 'RESET_EVENT_REGISTRATIONS_META';
export const RESET_EVENT_REGISTRATIONS_PAGE = 'RESET_EVENT_REGISTRATIONS_PAGE';

// Transactions

export const UPDATE_TRANSACTION_ERROR = 'UPDATE_TRANSACTION_ERROR';
export const UPDATE_TRANSACTION_REQUEST = 'UPDATE_TRANSACTION_REQUEST';
export const UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS';


// Assets
export const GET_ASSET_FILE_REQUEST = 'GET_ASSET_FILE_REQUEST';
export const GET_ASSET_FILE_ERROR = 'GET_ASSET_FILE_ERROR';
export const GET_ASSET_FILE_SUCCESS = 'GET_ASSET_FILE_SUCCESS';

// Users
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USER_REQUEST = 'GET_USERS_REQUEST';
export const GET_USER_ERROR = 'GET_USERS_ERROR';
export const GET_USER_SUCCESS = 'GET_USERS_SUCCESS';
export const RESET_USERS_LIST_META = 'RESET_USERS_LIST_META';
export const RESET_USERS_LIST_PAGE = 'RESET_USERS_LIST_PAGE';

// Check-in Admin
export const GET_CHECK_IN_ADMIN_REQUEST = 'GET_CHECK_IN_ADMIN_REQUEST';
export const GET_CHECK_IN_ADMIN_SUCCESS = 'GET_CHECK_IN_ADMIN_SUCCESS';
export const GET_CHECK_IN_ADMIN_ERROR = 'GET_CHECK_IN_ADMIN_ERROR';
export const RESET_CHECK_IN_ADMIN_PAGE = 'RESET_CHECK_IN_ADMIN_PAGE';
export const RESET_CHECK_IN_ADMIN_PAGE_FORM = 'RESET_CHECK_IN_ADMIN_PAGE_FORM';
export const RESET_CHECK_IN_ADMIN_PAGE_META = 'RESET_CHECK_IN_ADMIN_PAGE_META';
export const SUBMIT_CHECK_IN_ADMIN_FORM_REQUEST = 'SUBMIT_CHECK_IN_ADMIN_FORM_REQUEST';
export const SUBMIT_CHECK_IN_ADMIN_FORM_SUCCESS = 'SUBMIT_CHECK_IN_ADMIN_FORM_SUCCESS';
export const SUBMIT_CHECK_IN_ADMIN_FORM_ERROR = 'SUBMIT_CHECK_IN_ADMIN_FORM_ERROR';

// User's Events
export const GET_USER_EVENT_REQUEST = 'GET_USER_EVENT_REQUEST';
export const GET_USER_EVENT_ERROR = 'GET_USER_EVENT_ERROR';
export const GET_USER_EVENT_SUCCESS = 'GET_USER_EVENT_SUCCESS';
export const RESET_USER_EVENT = 'RESET_USER_EVENT';

// User's Coupons
export const GET_USER_COUPON_REQUEST = 'GET_USER_COUPON_REQUEST';
export const GET_USER_COUPON_ERROR = 'GET_USER_COUPON_ERROR';
export const GET_USER_COUPON_SUCCESS = 'GET_USER_COUPON_SUCCESS';
export const RESET_USER_COUPON = 'RESET_USER_COUPON';

// User's Parking Priviliges
export const GET_USER_PARKING_PRIVILIGES_REQUEST = 'GET_USER_PARKING_PRIVILIGES_REQUEST';
export const GET_USER_PARKING_PRIVILIGES_ERROR = 'GET_USER_PARKING_PRIVILIGES_ERROR';
export const GET_USER_PARKING_PRIVILIGES_SUCCESS = 'GET_USER_PARKING_PRIVILIGES_SUCCESS';
export const RESET_USER_PARKING_PRIVILIGES = 'RESET_USER_PARKING_PRIVILIGES';

// User's Notifications
export const GET_USER_NOTIFICATIONS_REQUEST = 'GET_USER_NOTIFICATIONS_REQUEST';
export const GET_USER_NOTIFICATIONS_ERROR = 'GET_USER_NOTIFICATIONS_ERROR';
export const GET_USER_NOTIFICATIONS_SUCCESS = 'GET_USER_NOTIFICATIONS_SUCCESS';
export const RESET_USER_NOTIFICATIONS = 'RESET_USER_NOTIFICATIONS';

// Admins
export const GET_ADMINS_LIST_PAGE_REQUEST = 'GET_ADMINS_LIST_PAGE_REQUEST';
export const GET_ADMINS_LIST_PAGE_ERROR = 'GET_ADMINS_LIST_PAGE_ERROR';
export const GET_ADMINS_LIST_PAGE_SUCCESS = 'GET_ADMINS_LIST_PAGE_SUCCESS';
export const RESET_ADMINS_LIST_PAGE_META = 'RESET_ADMINS_LIST_PAGE_META';
export const RESET_ADMINS_LIST_PAGE = 'RESET_ADMINS_LIST_PAGE';

// Admins Detail Page
export const GET_ADMIN_DETAIL_REQUEST = 'GET_ADMIN_DETAIL_REQUEST';
export const GET_ADMIN_DETAIL_SUCCESS = 'GET_ADMIN_DETAIL_SUCCESS';
export const GET_ADMIN_DETAIL_ERROR = 'GET_ADMIN_DETAIL_ERROR';
export const SUBMIT_ADMIN_DETAIL_REQUEST = 'SUBMIT_ADMIN_DETAIL_REQUEST';
export const SUBMIT_ADMIN_DETAIL_SUCCESS = 'SUBMIT_ADMIN_DETAIL_SUCCESS';
export const SUBMIT_ADMIN_DETAIL_ERROR = 'SUBMIT_ADMIN_DETAIL_ERROR';
export const RESET_ADMIN_DETAIL_META = 'RESET_ADMIN_DETAIL_META';
export const RESET_ADMIN_DETAIL_PAGE = 'RESET_ADMIN_DETAIL_PAGE';

// restaurant
export const GET_RESTAURANTS_PAGE_REQUEST = 'GET_RESTAURANTS_PAGE_REQUEST';
export const GET_RESTAURANTS_PAGE_SUCCESS = 'GET_RESTAURANTS_PAGE_SUCCESS';
export const GET_RESTAURANTS_PAGE_ERROR = 'GET_RESTAURANTS_PAGE_ERROR';
export const RESET_RESTAURANTS_PAGE_META = 'RESET_RESTAURANTS_PAGE_META';
export const RESET_RESTAURANTS_PAGE = 'RESET_RESTAURANTS_PAGE';

// merchant
export const GET_MERCHANT_REQUEST = 'GET_MERCHANT_REQUEST';
export const GET_MERCHANT_SUCCESS = 'GET_MERCHANT_SUCCESS';
export const GET_MERCHANT_ERROR = 'GET_MERCHANT_ERROR';
export const RESET_MERCHANT_PAGE = 'RESET_MERCHANT_PAGE';
export const RESET_MERCHANT_PAGE_FORM = 'RESET_MERCHANT_PAGE_FORM';
export const RESET_MERCHANT_PAGE_META = 'RESET_MERCHANT_PAGE_META';
export const SUBMIT_MERCHANT_FORM_REQUEST = 'SUBMIT_MERCHANT_FORM_REQUEST';
export const SUBMIT_MERCHANT_FORM_SUCCESS = 'SUBMIT_MERCHANT_FORM_SUCCESS';
export const SUBMIT_MERCHANT_FORM_ERROR = 'SUBMIT_MERCHANT_FORM_ERROR';

// General Settings Page
export const GET_GENERAL_SETTINGS_REQUEST = 'GET_GENERAL_SETTINGS_REQUEST';
export const GET_GENERAL_SETTINGS_ERROR = 'GET_GENERAL_SETTINGS_ERROR';
export const GET_GENERAL_SETTINGS_SUCCESS = 'GET_GENERAL_SETTINGS_SUCCESS';

export const SUBMIT_GENERAL_SETTINGS_REQUEST = 'SUBMIT_GENERAL_SETTINGS_REQUEST';
export const SUBMIT_GENERAL_SETTINGS_ERROR = 'SUBMIT_GENERAL_SETTINGS_ERROR';
export const SUBMIT_GENERAL_SETTINGS_SUCCESS = 'SUBMIT_GENERAL_SETTINGS_SUCCESS';

export const RESET_GENERAL_SETTINGS_PAGE_META = 'RESET_GENERAL_SETTINGS_PAGE_META';
export const RESET_GENERAL_SETTINGS_PAGE = 'RESET_GENERAL_SETTINGS_PAGE';

// Parking Privilege List Page
export const GET_PARKING_PRIVILEGES_LIST_REQUEST = 'GET_PARKING_PRIVILEGES_LIST_REQUEST';
export const GET_PARKING_PRIVILEGES_LIST_SUCCESS = 'GET_PARKING_PRIVILEGES_LIST_SUCCESS';
export const GET_PARKING_PRIVILEGES_LIST_ERROR = 'GET_PARKING_PRIVILEGES_LIST_ERROR';
export const RESET_PARKING_PRIVILEGES_LIST_META = 'RESET_PARKING_PRIVILEGES_LIST_META';
export const RESET_PARKING_PRIVILEGES_LIST_PAGE = 'RESET_PARKING_PRIVILEGES_LIST_PAGE';

// Parking Privilege Basic Page
export const GET_PARKING_PRIVILEGE_BASIC_REQUEST = 'GET_PARKING_PRIVILEGE_BASIC_REQUEST';
export const GET_PARKING_PRIVILEGE_BASIC_SUCCESS = 'GET_PARKING_PRIVILEGE_BASIC_SUCCESS';
export const GET_PARKING_PRIVILEGE_BASIC_ERROR = 'GET_PARKING_PRIVILEGE_BASIC_ERROR';
export const SUBMIT_PARKING_PRIVILEGE_BASIC_REQUEST = 'SUBMIT_PARKING_PRIVILEGE_BASIC_REQUEST';
export const SUBMIT_PARKING_PRIVILEGE_BASIC_SUCCESS = 'SUBMIT_PARKING_PRIVILEGE_BASIC_SUCCESS';
export const SUBMIT_PARKING_PRIVILEGE_BASIC_ERROR = 'SUBMIT_PARKING_PRIVILEGE_BASIC_ERROR';
export const RESET_PARKING_PRIVILEGE_BASIC_META = 'RESET_PARKING_PRIVILEGE_BASIC_META';
export const RESET_PARKING_PRIVILEGE_BASIC_PAGE = 'RESET_PARKING_PRIVILEGE_BASIC_PAGE';

// ParkingPrivilegeDetailPage.ParkingPrivilegeNotificationsPage
export const GET_PARKING_NOTIFICATIONS_ERROR = 'GET_PARKING_NOTIFICATIONS_ERROR';
export const GET_PARKING_NOTIFICATIONS_REQUEST = 'GET_PARKING_NOTIFICATIONS_REQUEST';
export const GET_PARKING_NOTIFICATIONS_SUCCESS = 'GET_PARKING_NOTIFICATIONS_SUCCESS';
export const RESET_PARKING_NOTIFICATIONS_META = 'RESET_PARKING_NOTIFICATIONS_META';
export const RESET_PARKING_NOTIFICATIONS_PAGE = 'RESET_PARKING_NOTIFICATIONS_PAGE';

// ParkingPrivilegeDetailPage.ParkingPrivilegeNotificationDetailPage
export const GET_PARKING_NOTIFICATION_DETAIL_ERROR = 'GET_PARKING_NOTIFICATION_DETAIL_ERROR';
export const GET_PARKING_NOTIFICATION_DETAIL_REQUEST = 'GET_PARKING_NOTIFICATION_DETAIL_REQUEST';
export const GET_PARKING_NOTIFICATION_DETAIL_SUCCESS = 'GET_PARKING_NOTIFICATION_DETAIL_SUCCESS';
export const RESET_PARKING_NOTIFICATION_DETAIL_META = 'RESET_PARKING_NOTIFICATION_DETAIL_META';
export const RESET_PARKING_NOTIFICATION_DETAIL_PAGE = 'RESET_PARKING_NOTIFICATION_DETAIL_PAGE';
export const SCHEDULE_PARKING_NOTIFICATION_DETAIL_ERROR = 'SCHEDULE_PARKING_NOTIFICATION_DETAIL_ERROR';
export const SCHEDULE_PARKING_NOTIFICATION_DETAIL_REQUEST = 'SCHEDULE_PARKING_NOTIFICATION_DETAIL_REQUEST';
export const SCHEDULE_PARKING_NOTIFICATION_DETAIL_SUCCESS = 'SCHEDULE_PARKING_NOTIFICATION_DETAIL_SUCCESS';
export const SEND_PARKING_NOTIFICATION_DETAIL_ERROR = 'SEND_PARKING_NOTIFICATION_DETAIL_ERROR';
export const SEND_PARKING_NOTIFICATION_DETAIL_REQUEST = 'SEND_PARKING_NOTIFICATION_DETAIL_REQUEST';
export const SEND_PARKING_NOTIFICATION_DETAIL_SUCCESS = 'SEND_PARKING_NOTIFICATION_DETAIL_SUCCESS';
export const SUBMIT_PARKING_NOTIFICATION_DETAIL_ERROR = 'SUBMIT_PARKING_NOTIFICATION_DETAIL_ERROR';
export const SUBMIT_PARKING_NOTIFICATION_DETAIL_REQUEST = 'SUBMIT_PARKING_NOTIFICATION_DETAIL_REQUEST';
export const SUBMIT_PARKING_NOTIFICATION_DETAIL_SUCCESS = 'SUBMIT_PARKING_NOTIFICATION_DETAIL_SUCCESS';

// ParkingPrivilegeDetailPage.ParkingPrivilegeUsagePage
export const GET_PARKING_USAGE_ERROR = 'GET_PARKING_USAGE_ERROR';
export const GET_PARKING_USAGE_REQUEST = 'GET_PARKING_USAGE_REQUEST';
export const GET_PARKING_USAGE_SUCCESS = 'GET_PARKING_USAGE_SUCCESS';
export const RESET_PARKING_USAGE_META = 'RESET_PARKING_USAGE_META';
export const RESET_PARKING_USAGE_PAGE = 'RESET_PARKING_USAGE_PAGE';

// Parking Admin
export const GET_PARKING_ADMIN_REQUEST = 'GET_PARKING_ADMIN_REQUEST';
export const GET_PARKING_ADMIN_SUCCESS = 'GET_PARKING_ADMIN_SUCCESS';
export const GET_PARKING_ADMIN_ERROR = 'GET_PARKING_ADMIN_ERROR';

export const RESET_PARKING_ADMIN_PAGE = 'RESET_PARKING_ADMIN_PAGE';
export const RESET_PARKING_ADMIN_PAGE_FORM = 'RESET_PARKING_ADMIN_PAGE_FORM';
export const RESET_PARKING_ADMIN_PAGE_META = 'RESET_PARKING_ADMIN_PAGE_META';

export const SUBMIT_PARKING_ADMIN_FORM_REQUEST = 'SUBMIT_PARKING_ADMIN_FORM_REQUEST';
export const SUBMIT_PARKING_ADMIN_FORM_SUCCESS = 'SUBMIT_PARKING_ADMIN_FORM_SUCCESS';
export const SUBMIT_PARKING_ADMIN_FORM_ERROR = 'SUBMIT_PARKING_ADMIN_FORM_ERROR';

// Coupon List Page
export const GET_COUPONS_LIST_REQUEST = 'GET_COUPONS_LIST_REQUEST';
export const GET_COUPONS_LIST_SUCCESS = 'GET_COUPONS_LIST_SUCCESS';
export const GET_COUPONS_LIST_ERROR = 'GET_COUPONS_LIST_ERROR';
export const RESET_COUPONS_LIST_META = 'RESET_COUPONS_LIST_META';
export const RESET_COUPONS_LIST_PAGE = 'RESET_COUPONS_LIST_PAGE';

// Coupon Basic Page
export const GET_COUPON_BASIC_REQUEST = 'GET_COUPON_BASIC_REQUEST';
export const GET_COUPON_BASIC_SUCCESS = 'GET_COUPON_BASIC_SUCCESS';
export const GET_COUPON_BASIC_ERROR = 'GET_COUPON_BASIC_ERROR';

export const GET_COUPON_BASIC_ASSET_FILE_REQUEST = 'GET_COUPON_BASIC_ASSET_FILE_REQUEST';
export const GET_COUPON_BASIC_ASSET_FILE_SUCCESS = 'GET_COUPON_BASIC_ASSET_FILE_SUCCESS';
export const GET_COUPON_BASIC_ASSET_FILE_ERROR = 'GET_COUPON_BASIC_ASSET_FILE_ERROR';

export const SUBMIT_COUPON_BASIC_REQUEST = 'SUBMIT_COUPON_BASIC_REQUEST';
export const SUBMIT_COUPON_BASIC_SUCCESS = 'SUBMIT_COUPON_BASIC_SUCCESS';
export const SUBMIT_COUPON_BASIC_ERROR = 'SUBMIT_COUPON_BASIC_ERROR';

export const RESET_COUPON_BASIC_META = 'RESET_COUPON_BASIC_META';
export const RESET_COUPON_BASIC_PAGE = 'RESET_COUPON_BASIC_PAGE';

// CouponDetailPage.CouponNotificationsPage
export const GET_COUPON_NOTIFICATIONS_ERROR = 'GET_COUPON_NOTIFICATIONS_ERROR';
export const GET_COUPON_NOTIFICATIONS_REQUEST = 'GET_COUPON_NOTIFICATIONS_REQUEST';
export const GET_COUPON_NOTIFICATIONS_SUCCESS = 'GET_COUPON_NOTIFICATIONS_SUCCESS';
export const RESET_COUPON_NOTIFICATIONS_META = 'RESET_COUPON_NOTIFICATIONS_META';
export const RESET_COUPON_NOTIFICATIONS_PAGE = 'RESET_COUPON_NOTIFICATIONS_PAGE';

// CouponDetailPage.CouponNotificationDetailPage
export const GET_COUPON_NOTIFICATION_DETAIL_ERROR = 'GET_COUPON_NOTIFICATION_DETAIL_ERROR';
export const GET_COUPON_NOTIFICATION_DETAIL_REQUEST = 'GET_COUPON_NOTIFICATION_DETAIL_REQUEST';
export const GET_COUPON_NOTIFICATION_DETAIL_SUCCESS = 'GET_COUPON_NOTIFICATION_DETAIL_SUCCESS';
export const RESET_COUPON_NOTIFICATION_DETAIL_META = 'RESET_COUPON_NOTIFICATION_DETAIL_META';
export const RESET_COUPON_NOTIFICATION_DETAIL_PAGE = 'RESET_COUPON_NOTIFICATION_DETAIL_PAGE';
export const SCHEDULE_COUPON_NOTIFICATION_DETAIL_ERROR = 'SCHEDULE_COUPON_NOTIFICATION_DETAIL_ERROR';
export const SCHEDULE_COUPON_NOTIFICATION_DETAIL_REQUEST = 'SCHEDULE_COUPON_NOTIFICATION_DETAIL_REQUEST';
export const SCHEDULE_COUPON_NOTIFICATION_DETAIL_SUCCESS = 'SCHEDULE_COUPON_NOTIFICATION_DETAIL_SUCCESS';
export const SEND_COUPON_NOTIFICATION_DETAIL_ERROR = 'SEND_COUPON_NOTIFICATION_DETAIL_ERROR';
export const SEND_COUPON_NOTIFICATION_DETAIL_REQUEST = 'SEND_COUPON_NOTIFICATION_DETAIL_REQUEST';
export const SEND_COUPON_NOTIFICATION_DETAIL_SUCCESS = 'SEND_COUPON_NOTIFICATION_DETAIL_SUCCESS';
export const SUBMIT_COUPON_NOTIFICATION_DETAIL_ERROR = 'SUBMIT_COUPON_NOTIFICATION_DETAIL_ERROR';
export const SUBMIT_COUPON_NOTIFICATION_DETAIL_REQUEST = 'SUBMIT_COUPON_NOTIFICATION_DETAIL_REQUEST';
export const SUBMIT_COUPON_NOTIFICATION_DETAIL_SUCCESS = 'SUBMIT_COUPON_NOTIFICATION_DETAIL_SUCCESS';

// CouponDetailPage.CouponCouponsPage
export const GET_COUPON_COUPONS_ERROR = 'GET_COUPON_COUPONS_ERROR';
export const GET_COUPON_COUPONS_REQUEST = 'GET_COUPON_COUPONS_REQUEST';
export const GET_COUPON_COUPONS_SUCCESS = 'GET_COUPON_COUPONS_SUCCESS';
export const DELETE_COUPON_COUPONS_REQUEST = 'DELETE_COUPON_COUPONS_REQUEST';
export const DELETE_COUPON_COUPONS_SUCCESS = 'DELETE_COUPON_COUPONS_SUCCESS';
export const DELETE_COUPON_COUPONS_ERROR = 'DELETE_COUPON_COUPONS_ERROR';
export const RESET_COUPON_COUPONS_META = 'RESET_COUPON_COUPONS_META';
export const RESET_COUPON_COUPONS_PAGE = 'RESET_COUPON_COUPONS_PAGE';

// Highlight Basic Page
export const GET_HIGHLIGHTS_REQUEST = 'GET_HIGHLIGHTS_REQUEST';
export const GET_HIGHLIGHTS_SUCCESS = 'GET_HIGHLIGHTS_SUCCESS';
export const GET_HIGHLIGHTS_ERROR = 'GET_HIGHLIGHTS_ERROR';
export const GET_HIGHLIGHT_BY_ID_REQUEST = 'GET_HIGHLIGHT_BY_ID_REQUEST';
export const GET_HIGHLIGHT_BY_ID_SUCCESS = 'GET_HIGHLIGHT_BY_ID_SUCCESS';
export const GET_HIGHLIGHT_BY_ID_ERROR = 'GET_HIGHLIGHT_BY_ID_ERROR';
export const GET_HIGHLIGHT_BASIC_ASSET_FILE_REQUEST = 'GET_HIGHLIGHT_BASIC_ASSET_FILE_REQUEST';
export const GET_HIGHLIGHT_BASIC_ASSET_FILE_SUCCESS = 'GET_HIGHLIGHT_BASIC_ASSET_FILE_SUCCESS';
export const GET_HIGHLIGHT_BASIC_ASSET_FILE_ERROR = 'GET_HIGHLIGHT_BASIC_ASSET_FILE_ERROR';
export const SUBMIT_HIGHLIGHT_BASIC_REQUEST = 'SUBMIT_HIGHLIGHT_BASIC_REQUEST';
export const SUBMIT_HIGHLIGHT_BASIC_SUCCESS = 'SUBMIT_HIGHLIGHT_BASIC_SUCCESS';
export const SUBMIT_HIGHLIGHT_BASIC_ERROR = 'SUBMIT_HIGHLIGHT_BASIC_ERROR';
export const RESET_HIGHLIGHT_BASIC_PAGE = 'RESET_HIGHLIGHT_BASIC_PAGE';
export const RESET_HIGHLIGHT_BASIC_META = 'RESET_HIGHLIGHT_BASIC_META';
export const RESET_HIGHLIGHT_PAGE_META = 'RESET_HIGHLIGHT_PAGE_META';
export const RESET_HIGHLIGHT_PAGE = 'RESET_HIGHLIGHT_PAGE';

// HighlightDetailPage.HighlightNotificationsPage
export const GET_HIGHLIGHT_NOTIFICATIONS_ERROR = 'GET_HIGHLIGHT_NOTIFICATIONS_ERROR';
export const GET_HIGHLIGHT_NOTIFICATIONS_REQUEST = 'GET_HIGHLIGHT_NOTIFICATIONS_REQUEST';
export const GET_HIGHLIGHT_NOTIFICATIONS_SUCCESS = 'GET_HIGHLIGHT_NOTIFICATIONS_SUCCESS';
export const RESET_HIGHLIGHT_NOTIFICATIONS_META = 'RESET_HIGHLIGHT_NOTIFICATIONS_META';
export const RESET_HIGHLIGHT_NOTIFICATIONS_PAGE = 'RESET_HIGHLIGHT_NOTIFICATIONS_PAGE';

// HighlightDetailPage.HighlightNotificationDetailPage
export const GET_HIGHLIGHT_NOTIFICATION_DETAIL_ERROR = 'GET_HIGHLIGHT_NOTIFICATION_DETAIL_ERROR';
export const GET_HIGHLIGHT_NOTIFICATION_DETAIL_REQUEST = 'GET_HIGHLIGHT_NOTIFICATION_DETAIL_REQUEST';
export const GET_HIGHLIGHT_NOTIFICATION_DETAIL_SUCCESS = 'GET_HIGHLIGHT_NOTIFICATION_DETAIL_SUCCESS';
export const RESET_HIGHLIGHT_NOTIFICATION_DETAIL_META = 'RESET_HIGHLIGHT_NOTIFICATION_DETAIL_META';
export const RESET_HIGHLIGHT_NOTIFICATION_DETAIL_PAGE = 'RESET_HIGHLIGHT_NOTIFICATION_DETAIL_PAGE';
export const SCHEDULE_HIGHLIGHT_NOTIFICATION_DETAIL_ERROR = 'SCHEDULE_HIGHLIGHT_NOTIFICATION_DETAIL_ERROR';
export const SCHEDULE_HIGHLIGHT_NOTIFICATION_DETAIL_REQUEST = 'SCHEDULE_HIGHLIGHT_NOTIFICATION_DETAIL_REQUEST';
export const SCHEDULE_HIGHLIGHT_NOTIFICATION_DETAIL_SUCCESS = 'SCHEDULE_HIGHLIGHT_NOTIFICATION_DETAIL_SUCCESS';
export const SEND_HIGHLIGHT_NOTIFICATION_DETAIL_ERROR = 'SEND_HIGHLIGHT_NOTIFICATION_DETAIL_ERROR';
export const SEND_HIGHLIGHT_NOTIFICATION_DETAIL_REQUEST = 'SEND_HIGHLIGHT_NOTIFICATION_DETAIL_REQUEST';
export const SEND_HIGHLIGHT_NOTIFICATION_DETAIL_SUCCESS = 'SEND_HIGHLIGHT_NOTIFICATION_DETAIL_SUCCESS';
export const SUBMIT_HIGHLIGHT_NOTIFICATION_DETAIL_ERROR = 'SUBMIT_HIGHLIGHT_NOTIFICATION_DETAIL_ERROR';
export const SUBMIT_HIGHLIGHT_NOTIFICATION_DETAIL_REQUEST = 'SUBMIT_HIGHLIGHT_NOTIFICATION_DETAIL_REQUEST';
export const SUBMIT_HIGHLIGHT_NOTIFICATION_DETAIL_SUCCESS = 'SUBMIT_HIGHLIGHT_NOTIFICATION_DETAIL_SUCCESS';

export const GET_POPUPS_REQUEST = 'GET_POPUPS_REQUEST';
export const GET_POPUPS_SUCCESS = 'GET_POPUPS_SUCCESS';
export const GET_POPUPS_ERROR = 'GET_POPUPS_ERROR';
export const SUBMIT_POPUP_BASIC_REQUEST = 'SUBMIT_POPUP_BASIC_REQUEST';
export const SUBMIT_POPUP_BASIC_SUCCESS = 'SUBMIT_POPUP_BASIC_SUCCESS';
export const SUBMIT_POPUP_BASIC_ERROR = 'SUBMIT_POPUP_BASIC_ERROR';
export const GET_POPUP_BY_ID_REQUEST = 'GET_POPUP_BY_ID_REQUEST';
export const GET_POPUP_BY_ID_SUCCESS = 'GET_POPUP_BY_ID_SUCCESS';
export const GET_POPUP_BY_ID_ERROR = 'GET_POPUP_BY_ID_ERROR';
export const GET_POPUP_BASIC_ASSET_FILE_ERROR = 'GET_POPUP_BASIC_ASSET_FILE_ERROR';
export const GET_POPUP_BASIC_ASSET_FILE_REQUEST = 'GET_POPUP_BASIC_ASSET_FILE_REQUEST';
export const GET_POPUP_BASIC_ASSET_FILE_SUCCESS = 'GET_POPUP_BASIC_ASSET_FILE_SUCCESS';
export const RESET_POPUP_BASIC_META = 'RESET_POPUP_BASIC_META';
export const RESET_POPUP_BASIC_PAGE = 'RESET_POPUP_BASIC_PAGE';
export const RESET_POPUP_PAGE_META = 'RESET_POPUP_PAGE_META';
export const RESET_POPUP_PAGE = 'RESET_POPUP_PAGE';

export const GET_PUSH_NOTIFICATIONS_REQUEST = 'GET_PUSH_NOTIFICATION_REQUEST';
export const GET_PUSH_NOTIFICATIONS_SUCCESS = 'GET_PUSH_NOTIFICATION_SUCCESS';
export const GET_PUSH_NOTIFICATIONS_ERROR = 'GET_PUSH_NOTIFICATION_ERROR';
export const RESET_PUSH_NOTIFICATIONS_PAGE_META = 'RESET_PUSH_NOTIFICATION_PAGE_META';
export const RESET_PUSH_NOTIFICATIONS_PAGE = 'RESET_PUSH_NOTIFICATION_PAGE';
export const RESET_PUSH_NOTIFICATION_BASIC_META = 'RESET_PUSH_NOTIFICATION_BASIC_META';
export const RESET_PUSH_NOTIFICATION_BASIC_PAGE = 'RESET_PUSH_NOTIFICATION_BASIC_PAGE';
export const SUBMIT_PUSH_NOTIFICATION_BASIC_REQUEST = 'SUBMIT_PUSH_NOTIFICATION_BASIC_REQUEST';
export const SUBMIT_PUSH_NOTIFICATION_BASIC_SUCCESS = 'SUBMIT_PUSH_NOTIFICATION_BASIC_SUCCESS';
export const SUBMIT_PUSH_NOTIFICATION_BASIC_ERROR = 'SUBMIT_PUSH_NOTIFICATION_BASIC_ERROR';
export const GET_PUSH_NOTIFICATION_BY_ID_REQUEST = 'GET_PUSH_NOTIFICATION_BY_ID_REQUEST';
export const GET_PUSH_NOTIFICATION_BY_ID_SUCCESS = 'GET_PUSH_NOTIFICATION_BY_ID_SUCCESS';
export const GET_PUSH_NOTIFICATION_BY_ID_ERROR = 'GET_PUSH_NOTIFICATION_BY_ID_ERROR';

// Segmentation Page
export const RESET_SEGMENTATION_PAGE = 'RESET_SEGMENTATION_PAGE';
export const RESET_SEGMENTATION_META = 'RESET_SEGMENTATION_META';

export const GET_SEGMENTATION_RECORD_REQUEST = 'GET_SEGMENTATION_RECORD_REQUEST';
export const GET_SEGMENTATION_RECORD_SUCCESS = 'GET_SEGMENTATION_RECORD_SUCCESS';
export const GET_SEGMENTATION_RECORD_ERROR = 'GET_SEGMENTATION_RECORD_ERROR';

export const GET_SEGMENTATION_ACAD_GROUPS_REQUEST = 'GET_SEGMENTATION_ACAD_GROUPS_REQUEST';
export const GET_SEGMENTATION_ACAD_GROUPS_SUCCESS = 'GET_SEGMENTATION_ACAD_GROUPS_SUCCESS';
export const GET_SEGMENTATION_ACAD_GROUPS_ERROR = 'GET_SEGMENTATION_ACAD_GROUPS_ERROR';

export const GET_SEGMENTATION_ACAD_PLANS_REQUEST = 'GET_SEGMENTATION_ACAD_PLANS_REQUEST';
export const GET_SEGMENTATION_ACAD_PLANS_SUCCESS = 'GET_SEGMENTATION_ACAD_PLANS_SUCCESS';
export const GET_SEGMENTATION_ACAD_PLANS_ERROR = 'GET_SEGMENTATION_ACAD_PLANS_ERROR';

export const GET_SEGMENTATION_ACCESS_GROUPS_REQUEST = 'GET_SEGMENTATION_ACCESS_GROUPS_REQUEST';
export const GET_SEGMENTATION_ACCESS_GROUPS_SUCCESS = 'GET_SEGMENTATION_ACCESS_GROUPS_SUCCESS';
export const GET_SEGMENTATION_ACCESS_GROUPS_ERROR = 'GET_SEGMENTATION_ACCESS_GROUPS_ERROR';

export const GET_SEGMENTATION_ACCESS_STUDENTS_INCLUDE_REQUEST = 'GET_SEGMENTATION_ACCESS_STUDENTS_INCLUDE_REQUEST';
export const GET_SEGMENTATION_ACCESS_STUDENTS_INCLUDE_SUCCESS = 'GET_SEGMENTATION_ACCESS_STUDENTS_INCLUDE_SUCCESS';
export const GET_SEGMENTATION_ACCESS_STUDENTS_INCLUDE_ERROR = 'GET_SEGMENTATION_ACCESS_STUDENTS_INCLUDE_ERROR';

export const GET_SEGMENTATION_ACCESS_STUDENTS_EXCLUDE_REQUEST = 'GET_SEGMENTATION_ACCESS_STUDENTS_EXCLUDE_REQUEST';
export const GET_SEGMENTATION_ACCESS_STUDENTS_EXCLUDE_SUCCESS = 'GET_SEGMENTATION_ACCESS_STUDENTS_EXCLUDE_SUCCESS';
export const GET_SEGMENTATION_ACCESS_STUDENTS_EXCLUDE_ERROR = 'GET_SEGMENTATION_ACCESS_STUDENTS_EXCLUDE_ERROR';

export const GET_SEGMENTATION_SEARCH_STUDENTS_INCLUDE_REQUEST = 'GET_SEGMENTATION_SEARCH_STUDENTS_INCLUDE_REQUEST';
export const GET_SEGMENTATION_SEARCH_STUDENTS_INCLUDE_SUCCESS = 'GET_SEGMENTATION_SEARCH_STUDENTS_INCLUDE_SUCCESS';
export const GET_SEGMENTATION_SEARCH_STUDENTS_INCLUDE_ERROR = 'GET_SEGMENTATION_SEARCH_STUDENTS_INCLUDE_ERROR';

export const GET_SEGMENTATION_SEARCH_STUDENTS_EXCLUDE_REQUEST = 'GET_SEGMENTATION_SEARCH_STUDENTS_EXCLUDE_REQUEST';
export const GET_SEGMENTATION_SEARCH_STUDENTS_EXCLUDE_SUCCESS = 'GET_SEGMENTATION_SEARCH_STUDENTS_EXCLUDE_SUCCESS';
export const GET_SEGMENTATION_SEARCH_STUDENTS_EXCLUDE_ERROR = 'GET_SEGMENTATION_SEARCH_STUDENTS_EXCLUDE_ERROR';

export const SUBMIT_SEGMENTATION_REQUEST = 'SUBMIT_SEGMENTATION_REQUEST';
export const SUBMIT_SEGMENTATION_SUCCESS = 'SUBMIT_SEGMENTATION_SUCCESS';
export const SUBMIT_SEGMENTATION_ERROR = 'SUBMIT_SEGMENTATION_ERROR';

export const UPLOAD_SEGMENTATION_REQUEST = 'UPLOAD_SEGMENTATION_REQUEST';
export const UPLOAD_SEGMENTATION_SUCCESS = 'UPLOAD_SEGMENTATION_SUCCESS';
export const UPLOAD_SEGMENTATION_ERROR = 'UPLOAD_SEGMENTATION_ERROR';

export const DOWNLOAD_EVENT_REPORTS_REQUEST = 'DOWNLOAD_EVENT_REPORTS_REQUEST';
export const DOWNLOAD_EVENT_REPORTS_ERROR = 'DOWNLOAD_EVENT_REPORTS_ERROR';
export const DOWNLOAD_EVENT_REPORTS_SUCCESS = 'DOWNLOAD_EVENT_REPORTS_SUCCESS';
export const RESET_DOWNLOAD_EVENT_REPORTS_META = 'RESET_DOWNLOAD_EVENT_REPORTS_META';
export const RESET_DOWNLOAD_EVENT_REPORTS_PAGE = 'RESET_DOWNLOAD_EVENT_REPORTS_PAGE';

export const DOWNLOAD_PARKING_REPORTS_REQUEST = 'DOWNLOAD_PARKING_REPORTS_REQUEST';
export const DOWNLOAD_PARKING_REPORTS_ERROR = 'DOWNLOAD_PARKING_REPORTS_ERROR';
export const DOWNLOAD_PARKING_REPORTS_SUCCESS = 'DOWNLOAD_PARKING_REPORTS_SUCCESS';

export const DOWNLOAD_PARKING_PRIVILEGE_REPORTS_REQUEST = 'DOWNLOAD_PARKING_PRIVILEGE_REPORTS_REQUEST';
export const DOWNLOAD_PARKING_PRIVILEGE_REPORTS_SUCCESS = 'DOWNLOAD_PARKING_PRIVILEGE_REPORTS_SUCCESS';
export const DOWNLOAD_PARKING_PRIVILEGE_REPORTS_ERROR = 'DOWNLOAD_PARKING_PRIVILEGE_REPORTS_ERROR';
export const RESET_DOWNLOAD_PARKING_PRIVILEGE_REPORTS_META = 'RESET_DOWNLOAD_PARKING_PRIVILEGE_REPORTS_META';
export const RESET_DOWNLOAD_PARKING_PRIVILEGE_REPORTS_PAGE = 'RESET_DOWNLOAD_PARKING_PRIVILEGE_REPORTS_PAGE';

export const DOWNLOAD_COUPON_REPORTS_REQUEST = 'DOWNLOAD_COUPON_REPORTS_REQUEST';
export const DOWNLOAD_COUPON_REPORTS_SUCCESS = 'DOWNLOAD_COUPON_REPORTS_SUCCESS';
export const DOWNLOAD_COUPON_REPORTS_ERROR = 'DOWNLOAD_COUPON_REPORTS_ERROR';
export const RESET_DOWNLOAD_COUPON_REPORTS_META = 'RESET_DOWNLOAD_COUPON_REPORTS_META';
export const RESET_DOWNLOAD_COUPON_REPORTS_PAGE = 'RESET_DOWNLOAD_COUPON_REPORTS_PAGE';